name: ci
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: clojure:openjdk-11-tools-deps
    steps:
      - uses: actions/checkout@v2
      - name: Run test
        run: clojure -M:test

  validate:
    runs-on: ubuntu-latest
    container:
      image: clojure:openjdk-11-tools-deps
    steps:
      - uses: actions/checkout@v2
      - name: Validate
        run: clojure -M:validate dev-resources/sample-validator

  lint:
    runs-on: ubuntu-latest
    container:
      image: clojure:openjdk-11-tools-deps
    steps:
      - uses: actions/checkout@v2
      - name: Run lint
        run: clojure -M:lint

  # ref: https://docs.github.com/en/free-pro-team@latest/actions/guides/publishing-docker-images
  # You can find the image on: https://hub.docker.com/r/xcoo/cruler
  snapshot-push:
    name: snapshot push
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [test, validate, lint]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: get tag version
        id: get_tag_version
        run: |
          sudo apt-get install libxml2-utils
          echo ::set-output \
            name=VERSION::$(xmllint --xpath "/*[local-name()='project']/*[local-name()='version']/text()" pom.xml)
      - name: snapshot push
        if: endsWith(steps.get_tag_version.outputs.VERSION, '-SNAPSHOT')
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: xcoo/cruler
          tags: ${{ steps.get_tag_version.outputs.VERSION }}
