---

name: deploy-clojars

on:
  push:
    tags: ['[0-9]+.[0-9]+.[0-9]+']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: clojure:openjdk-11-tools-deps
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: clojure -T:build jar :jar-file cruler.jar
      - name: Copy pom.xml
        run: cp target/classes/META-INF/maven/xcoo/cruler/pom.xml pom.xml
      - uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: |
            cruler.jar
            pom.xml

  deploy:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: clojure:openjdk-11-tools-deps
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v4.1.7
        with:
          name: build-output
      - name: Deploy
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
        run: clojure -M:deploy
