name: deploy-clojars
on: [ workflow_dispatch ]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: clojure:openjdk-11-tools-deps
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: clojure -X:depstar jar :jar cruler.jar
      - uses: actions/upload-artifact@v2
        with:
          name: jar
          path: cruler.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: clojure:openjdk-11-tools-deps
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: jar
      - name: Deploy
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
        run: clj -Adeploy
